### ISSUE TITLE
Validating defaults is problematic

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#1056]
When we set defaults with the config system, we try to validate them. This is problematic when the validation uses the object instance in the validation.

Here's an example with a weight solver:
```python
with nengo.Network() as model:
    model.config[nengo.Connection].solver = nengo.solvers.LstsqL2(weights=True)
    c = nengo.Connection(nengo.Ensemble(10, 1), nengo.Ensemble(10, 1))
```

Setting a default function is also problematic. Currently it fails because `function` isn't even a Parameter on the `Connection` class; we hide it in the `function_info` parameter. But even if we fix this, it will fail for the reason above: we use the `Connection` instance when validating `function`.
```python
with nengo.Network() as model:
    model.config[nengo.Connection].function = lambda x: x**2
    c = nengo.Connection(nengo.Ensemble(10, 1), nengo.Ensemble(10, 1))
```

**Comment by hunse** [comment]
My proposed solution is to simply not validate defaults. We will validate them when using them to create an object. This will still happen early (i.e. before the build process), so it shouldn't be a big deal.

**Comment by tbekolay** [comment]
We used to not validate them, but people found it confusing when they were allowed to do things like:
```python
net.config[nengo.Ensemble].max_rates = np.random.rand(5) * 100
```
and then would get a failure with `nengo.Ensemble(10, 1)` even though they didn't change `max_rates`. The failure being so far away from the error message makes it hard to debug...

**Comment by hunse** [comment]
The first part of this is fixed with the `coerce_defaults` attribute on Parameters.

Setting a default for `Connection.function` still doesn't work because we use `function_info` internally, as stated above. I don't think this is a very high-demand thing, so maybe we don't worry about it. However, it would be nice to have a nicer error if you try to set a default for `Connection.function` (or any other attribute that's not a Parameter). Right now, if you try to set a `function` default (or `size_out`, etc.) you get:
```
Traceback (most recent call last):
  File "test_function_default.py", line 9, in <module>
    model.config[nengo.Connection].size_out = 3
  File "/data/eric/workspace/nengo/nengo/config.py", line 71, in __setattr__
    if not param.configurable:
AttributeError: 'property' object has no attribute 'configurable'
```
