### ISSUE TITLE
SPA gaiting failure

### ISSUE THREAD

**Issue by teslar** [nengo/nengo#1098]
Hey,

this causes a funky compile error (Terry is informed :) ):
```
Traceback (most recent call last):
  File "/Users/teslar/git/nengo/nengo_gui/nengo_gui/page.py", line 438, in build
    self.sim = backend.Simulator(self.model)
  File "/Users/teslar/git/nengo/nengo/nengo/simulator.py", line 137, in __init__
    self.model.build(network)
  File "/Users/teslar/git/nengo/nengo/nengo/builder/builder.py", line 119, in build
    return Builder.build(self, obj, *args, **kwargs)
  File "/Users/teslar/git/nengo/nengo/nengo/builder/builder.py", line 211, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/Users/teslar/git/nengo/nengo/nengo/builder/network.py", line 72, in build_network
    model.build(subnetwork)
  File "/Users/teslar/git/nengo/nengo/nengo/builder/builder.py", line 119, in build
    return Builder.build(self, obj, *args, **kwargs)
  File "/Users/teslar/git/nengo/nengo/nengo/builder/builder.py", line 211, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/Users/teslar/git/nengo/nengo/nengo/builder/network.py", line 84, in build_network
    model.build(conn)
  File "/Users/teslar/git/nengo/nengo/nengo/builder/builder.py", line 119, in build
    return Builder.build(self, obj, *args, **kwargs)
  File "/Users/teslar/git/nengo/nengo/nengo/builder/builder.py", line 211, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/Users/teslar/git/nengo/nengo/nengo/builder/connection.py", line 213, in build_connection
    model.sig[conn]['in'] = get_prepost_signal(is_pre=True)
  File "/Users/teslar/git/nengo/nengo/nengo/builder/connection.py", line 205, in get_prepost_signal
    % (conn, 'pre' if is_pre else 'post', target))
BuildError: Building <Connection from <Ensemble "gate[6]"> to <Neurons of <Ensemble "channel_6_memory_0">>>: the 'pre' object <Ensemble "gate[6]"> is not in the model, or has a size of zero.
```

```python
import nengo
import nengo.spa as spa
import numpy as np

D = 32  # the dimensionality of the vectors

model = spa.SPA()

vocab = spa.Vocabulary(D)
vocab2 = spa.Vocabulary(D)

with model:
    
    vocab.parse("ON")
    vocab2.parse("A+B+C+D+E")

    """    
    def signal(t):
        if t < 0.25:
            return "ON"
        else:
            return "OFF"
    """
   
    inp = nengo.Node([0])
    deriv = nengo.Ensemble(n_neurons= 200, dimensions = 1)
    deriv2 = nengo.Ensemble(n_neurons= 200, dimensions = 1)
    
    model.vision = spa.State(D)
    model.switch = spa.State(D, vocab=vocab)
    model.memory = spa.State(D, feedback=1, feedback_synapse=0.05)
    model.cleanup = spa.AssociativeMemory(input_vocab=vocab2)

    
    nengo.Connection(inp, deriv)
    nengo.Connection(inp, deriv, transform=-1, synapse=0.05)

    nengo.Connection(deriv, deriv2, function= lambda x: np.square(x))
    nengo.Connection(deriv2, model.switch.input, transform=10*vocab["ON"].v.reshape(D, 1))


    actions = spa.Actions(
        'dot(memory, A)+dot(switch, ON)-1 --> memory=B-A, switch=3*OFF',
        'dot(memory, B)+dot(switch, ON)-1 --> memory=C-B, switch=3*OFF',
        'dot(memory, C)+dot(switch, ON)-1 --> memory=D-C, switch=3*OFF',
        'dot(memory, D)+dot(switch, ON)-1 --> memory=E-D, switch=3*OFF',
        'dot(memory, E)+dot(switch, ON)-1 --> memory=A-E, switch=3*OFF',
        'dot(vision, A) --> memory=vision',
        '0.5 --> cleanup=memory, memory=cleanup'
        )

    model.bg = spa.BasalGanglia(actions)
    model.thalamus = spa.Thalamus(model.bg)
#    model.inp = spa.Input(switch=signal)
```

**Comment by jgosmann** [comment]
Not sure if it is worth the effort to fix this. With PR #1014 this bug might be solved already or will at least require a separate fix.

**Comment by jgosmann** [comment]
The problem here seems to be the recurrency from cleanup to memory and memory to cleanup.

**Comment by jgosmann** [comment]
It seems that the cause is the following:

* The thalamus gating ensemble will be created within either the `cleanup` or the `memory` network (but not both).
* A connection to the gate will be added with in both networks 
* The two networks are on the same level of the hierarchy which makes the build order undefined. Nengo might build the network without the gate ensemble first which involves building the connection to the gate ensemble. That fails in this case because the gate ensemble has not been built yet.

**Comment by jgosmann** [comment]
@teslar, you can try the `fix-1098` branch. It should solve the problem.
