### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1156]
With this model

``` python
with nengo.Network(seed=seed, label="Circular convolution") as model:
    v = np.random.randn(2, dimensions)
    v /= np.linalg.norm(v, axis=1)[:, None]

    model.input_a = nengo.Node(v[0])
    model.input_b = nengo.Node(v[1])

    model.cconv = nengo.networks.CircularConvolution(
        n_neurons=n_neurons, dimensions=dimensions)
    nengo.Connection(model.input_a, model.cconv.A)
    nengo.Connection(model.input_b, model.cconv.B)

    model.p_input_a = nengo.Probe(model.input_a, synapse=0.01)
    model.p_input_b = nengo.Probe(model.input_b, synapse=0.01)
    model.p_output = nengo.Probe(model.cconv.output, synapse=0.01)
```

I get this strange error:

```
Traceback (most recent call last):
  File "gosmann_frontiers2016/benchmarks/circ_conv.py", line 28, in <module>
    with nengo.Simulator(model) as sim:
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2016/lib/python3.5/site-packages/nengo/simulator.py", line 131, in __init__
    self.model.build(network)
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2016/lib/python3.5/site-packages/nengo/builder/builder.py", line 119, in build
    return Builder.build(self, obj, *args, **kwargs)
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2016/lib/python3.5/site-packages/nengo/builder/builder.py", line 211, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2016/lib/python3.5/site-packages/nengo/builder/network.py", line 91, in build_network
    model.build(conn)
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2016/lib/python3.5/site-packages/nengo/builder/builder.py", line 119, in build
    return Builder.build(self, obj, *args, **kwargs)
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2016/lib/python3.5/site-packages/nengo/builder/builder.py", line 211, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2016/lib/python3.5/site-packages/nengo/builder/connection.py", line 264, in build_connection
    tag="%s.weights_elementwiseinc" % conn))
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2016/lib/python3.5/site-packages/nengo/builder/builder.py", line 106, in add_op
    op.init_signals(signals)
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2016/lib/python3.5/site-packages/nengo/builder/operator.py", line 162, in init_signals
    signals.init(sig)
  File "/home/jgosmann/.virtualenvs/gosmann-frontiers2016/lib/python3.5/site-packages/nengo/builder/signal.py", line 255, in init
    dtype=x.dtype, buffer=self[signal.base].data)
ValueError: strides is incompatible with shape of requested array and size of buffer
```

Might be a screw up on my side (rather than on the Nengo side), but in that case we might be able to provide a better error message.

**Comment by jgosmann** [comment]
It's fixed by making a copy of the input arrays:
```python
model.input_a = nengo.Node(np.array(v[0]))
model.input_b = nengo.Node(np.array(v[1]))
```

**Comment by hunse** [comment]
Is this in Python 2 or Python 3?

**Comment by jgosmann** [comment]
Python 3

**Comment by hunse** [comment]
Ok, then I think it's unrelated to the strides issue I've been having in Nengo OCL. Just checking!

**Comment by jgosmann** [comment]
So, I figured out what's causing this (but I'm not sure how to fix it yet):
An array view is used as `initial_value` for a signal (that is not a view). From that signal a signal view is created which creates a view of the `initial_value` which results in a view of view of an array. But Numpy collapses this hierarchy to just one view of a signal. When initializing the signal dict the view offset will thus be calculated relative to the base array, but the (first) view of the array will be used for the data array and thus the offset is invalid.
