### ISSUE TITLE
Cache error on sharcnet

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1188]
```
Traceback (most recent call last):
  File "/work/jgosmann/tcm/tcm_immediate/tcm_immediate:process:0.py", line 16, in <module>
    Worker(store=task.store).start(execute, '/work/jgosmann/tcm/tcm_immediate/in/0.npz', '/work/jgosmann/tcm/tcm_immediate/out/0.npz')
  File "/home/jgosmann/software/psyrun/psyrun/processing.py", line 150, in start
    return_data=False)
  File "/home/jgosmann/software/psyrun/psyrun/mapper.py", line 135, in map_pspace_hdd_backed
    store.append(filename, dict_concat((get_result(fn, p),)))
  File "/home/jgosmann/software/psyrun/psyrun/mapper.py", line 36, in get_result
    result.update(fn(**params))
  File "/home/jgosmann/Documents/projects/research/tcm/psy-tasks/task_tcm_immediate.py", line 38, in execute
    return NeuralTCM().run_single_action('evaluate', p)[0]
  File "build/bdist.linux-x86_64/egg/ctn_benchmark/pipeline.py", line 92, in run_single_action
  File "build/bdist.linux-x86_64/egg/ctn_benchmark/pipeline.py", line 67, in invoke_action
  File "build/bdist.linux-x86_64/egg/ctn_benchmark/procstep.py", line 124, in process_all
  File "build/bdist.linux-x86_64/egg/ctn_benchmark/procstep.py", line 166, in process
  File "build/bdist.linux-x86_64/egg/ctn_benchmark/procstep.py", line 143, in next
  File "build/bdist.linux-x86_64/egg/ctn_benchmark/procstep.py", line 168, in process
  File "build/bdist.linux-x86_64/egg/ctn_benchmark/common_steps.py", line 190, in process_item
  File "/home/jgosmann/.virtualenvs/saw-bleeding-edge/lib/python2.7/site-packages/nengo-2.1.1.dev0-py2.7.egg/nengo/simulator.py", line 147, in __init__
    cache.shrink()
  File "/home/jgosmann/.virtualenvs/saw-bleeding-edge/lib/python2.7/site-packages/nengo-2.1.1.dev0-py2.7.egg/nengo/cache.py", line 211, in __exit__
    return self._index.__exit__(exc_type, exc_value, traceback)
  File "/home/jgosmann/.virtualenvs/saw-bleeding-edge/lib/python2.7/site-packages/nengo-2.1.1.dev0-py2.7.egg/nengo/cache.py", line 114, in __exit__
    self.sync()
  File "/home/jgosmann/.virtualenvs/saw-bleeding-edge/lib/python2.7/site-packages/nengo-2.1.1.dev0-py2.7.egg/nengo/cache.py", line 130, in sync
    self._index = self._load_index()
  File "/home/jgosmann/.virtualenvs/saw-bleeding-edge/lib/python2.7/site-packages/nengo-2.1.1.dev0-py2.7.egg/nengo/cache.py", line 120, in _load_index
    return pickle.load(f)
EOFError
```

```
saw-login1:tcm|context3> ls -lh /scratch/jgosmann/nengo-decoder-cache/
total 38M
drwxr-xr-x 2 jgosmann celiasmi 4.0K Oct 31 14:54 00
drwxr-xr-x 2 jgosmann celiasmi 4.0K Oct 31 15:01 01
drwxr-xr-x 2 jgosmann celiasmi 4.0K Oct 31 14:56 02
drwxr-xr-x 2 jgosmann celiasmi 4.0K Nov  4 11:54 03
[...]
drwxr-xr-x 2 jgosmann celiasmi 4.0K Oct 31 14:54 fd
drwxr-xr-x 2 jgosmann celiasmi 4.0K Nov  4 11:40 fe
drwxr-xr-x 2 jgosmann celiasmi 4.0K Oct 31 14:54 ff
-rw-r--r-- 1 jgosmann celiasmi  37M Nov  7 11:29 index
-rw-r--r-- 1 jgosmann celiasmi    4 Aug 30 09:17 legacy.txt

saw-login1:tcm|context3> cat /scratch/jgosmann/nengo-decoder-cache/legacy.txt 
1.2
```

**Comment by jgosmann** [comment]
I'm closing this for now because this is happening with a Nengo versions based on 2.1.1 and there have been some other fixes in the mean time.
