### ISSUE TITLE
Unhandled situation in new-spa action handling

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo#1201]
I just found an example that the new spa parser doesn't handle:

```python
import nengo
import nengo.spa as spa

D = 32

model = spa.SPA()
with model:
    model.vector = spa.State(D)
    model.scalar = spa.State(1)

    actions = spa.Actions(
        'dot(vector,A) + scalar --> vector=B'
        )

    model.bg = spa.BasalGanglia(actions)
    model.thalamus = spa.Thalamus(model.bg)
```

This worked in the old system (i.e. current master)

Here's the error:

```
Traceback (most recent call last):
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\page.py", line 219, in execute
    exec(compiled, code_locals)
  File "<nengo_gui_compiled>", line 61, in <module>
  File "c:\users\terry\documents\github\nengo\nengo\spa\thalamus.py", line 112, in __init__
    self.bg.actions.process()
  File "c:\users\terry\documents\github\nengo\nengo\spa\actions.py", line 227, in process
    self.process_new_actions(self.vocabs, *self.args, **self.kwargs)
  File "c:\users\terry\documents\github\nengo\nengo\spa\actions.py", line 232, in process_new_actions
    action.infer_types(self.construction_context.root_module, None)
  File "c:\users\terry\documents\github\nengo\nengo\spa\spa_ast.py", line 1022, in infer_types
    self.condition.infer_types(root_module, context_type)
  File "c:\users\terry\documents\github\nengo\nengo\spa\spa_ast.py", line 565, in infer_types
    self.lhs.infer_types(root_module, context_type)
  File "c:\users\terry\documents\github\nengo\nengo\spa\spa_ast.py", line 763, in infer_types
    self.lhs.type, self.rhs.type, self))
SpaTypeError: Incompatible types TVocabulary<32-dimensional vocab at 0x39b74908> and TVocabulary<1-dimensional vocab at 0x39b74e48> in dot product 'dot(vector, A)'.
```

**EDIT:** as @jgosmann points out below, this is desired behaviour

**Comment by tcstewar** [comment]
And another unhandled case:

```python
import nengo
import nengo.spa as spa

model = spa.SPA()
with model:
    model.state1 = spa.State(16)
    model.state2 = spa.State(32)

    actions = spa.Actions(
        '0.5 --> state1 = translate(state2)*2'    # this works
        '0.5 --> state1 = 2*translate(state2)'    # this doesn't
        )

    model.bg = spa.BasalGanglia(actions)
    model.thalamus = spa.Thalamus(model.bg)
```

Here's the error:

```
Traceback (most recent call last):
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\page.py", line 219, in execute
    exec(compiled, code_locals)
  File "<nengo_gui_compiled>", line 57, in <module>
  File "c:\users\terry\documents\github\nengo\nengo\spa\actions.py", line 197, in __init__
    self.parse(self.vocabs, *self.args, **self.kwargs)
  File "c:\users\terry\documents\github\nengo\nengo\spa\actions.py", line 204, in parse
    self._parse_and_add(parser, action)
  File "c:\users\terry\documents\github\nengo\nengo\spa\actions.py", line 241, in _parse_and_add
    action, len(self.actions), strict=False, name=name)
  File "c:\users\terry\documents\github\nengo\nengo\spa\actions.py", line 65, in parse_action
    self.parse_effects(effects, channeled=True), index, name=name)
  File "c:\users\terry\documents\github\nengo\nengo\spa\actions.py", line 118, in parse_effects
    for effect in parsed])
  File "c:\users\terry\documents\github\nengo\nengo\spa\actions.py", line 140, in parse_effect
    Sink(sink.strip()), self.parse_expr(source), channeled=channeled)
  File "c:\users\terry\documents\github\nengo\nengo\spa\actions.py", line 154, in parse_expr
    return eval(expr, {}, self)
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'int' and 'Translate'
```

**Comment by jgosmann** [comment]
I would consider the first case as a feature not a bug. We could treat 1d SPs as scalars, but to me there is a semantic difference between a scalar and a Semantic Pointer. So I was thinking to introduce a `spa.Scalar` module instead.

The second thing is indeed a bug. I assume it can be solved by adding a `__rmul__` method to `Translate` (or one of the base classes).

**Comment by tcstewar** [comment]
> I would consider the first case as a feature not a bug. We could treat 1d SPs as scalars, but to me there is a semantic difference between a scalar and a Semantic Pointer. So I was thinking to introduce a spa.Scalar module instead.

I can definitely see that approach as well.  Would the idea be something like that module would declare (in ```self.outputs```) a 1-dimensional output, whose vocabulary is None?  That sort of thing would work well in all the cases I've wanted to use this....

**Comment by jgosmann** [comment]
Yes, that's what for example `spa.Compare` is already doing. I also noticed that the [`spa.Scalar` already exists in `new-spa`](https://github.com/nengo/nengo/blob/new-spa/nengo/spa/scalar.py). So the following works:

```python
import nengo
import nengo.spa as spa

D = 32

model = spa.SPA()
with model:
    model.vector = spa.State(D)
    model.scalar = spa.Scalar()

    actions = spa.Actions(
        'dot(vector,A) + scalar --> vector=B'
        )

    model.bg = spa.BasalGanglia(actions)
    model.thalamus = spa.Thalamus(model.bg)
```

**Comment by tcstewar** [comment]
Sweet!  That makes sense to me.

I'll take a stab at the ```__rmul__``` fix for the other issue....

**Comment by tcstewar** [comment]
> I would consider the first case as a feature not a bug. We could treat 1d SPs as scalars, but to me there is a semantic difference between a scalar and a Semantic Pointer. So I was thinking to introduce a spa.Scalar module instead.

Might it be possible to get a clearer error message for this?  The error message currently generated is a bit misleading, in that it focuses attention on the ```dot(vector,A)``` part, but that's not what's causing the problem here....

```
SpaTypeError: Incompatible types TVocabulary<32-dimensional vocab at 0x39b74908> and TVocabulary<1-dimensional vocab at 0x39b74e48> in dot product 'dot(vector, A)'.
```

**Comment by jgosmann** [comment]
That's a good point, I have to look into this.

**Comment by jgosmann** [comment]
> I'll take a stab at the __rmul__ fix for the other issue....

The actual issue was slightly different. I fixed it locally and will make a PR once I figured out how to improve the error message.

**Comment by jgosmann** [comment]
(Also neither of the action lines did work.)

**Comment by jgosmann** [comment]
Would
```
nengo.exceptions.SpaTypeError: Condition 'dot(vector, A) + scalar' does not evaluate to a scalar.
```
be a better error message?

**Comment by jgosmann** [comment]
I decided to get this completely right and the error message will be:
```
nengo.exceptions.SpaTypeError: Incompatible types TScalar and TVocabulary<1-dimensional vocab at 0x7f3adc135080> in operation 'dot(vector, A) + scalar'.
```
