### ISSUE TITLE
Potentially cache related crash on sharcnet

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1250]
I had a bunch of jobs on Sharcnet crash with this error:
```
/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/learning_rules.py:105: UserWarning: This learning rate is very high, and can result in floating point errors from too much current.
  warnings.warn("This learning rate is very high, and can result "
Traceback (most recent call last):
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/cache.py", line 375, in cached_solver
    path, start, end = self._index[key]
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/cache.py", line 97, in __getitem__
    return self._index[key]
KeyError: 'c840a88c96083c9a7e6be51b5f55ea5ac8b24e23'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/simulator.py", line 144, in __init__
    self.model.build(network)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/builder/builder.py", line 127, in build
    return Builder.build(self, obj, *args, **kwargs)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/builder/builder.py", line 219, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/builder/network.py", line 72, in build_network
    model.build(subnetwork)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/builder/builder.py", line 127, in build
    return Builder.build(self, obj, *args, **kwargs)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/builder/builder.py", line 219, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/builder/network.py", line 72, in build_network
    model.build(subnetwork)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/builder/builder.py", line 127, in build
    return Builder.build(self, obj, *args, **kwargs)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/builder/builder.py", line 219, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/builder/network.py", line 84, in build_network
    model.build(conn)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/builder/builder.py", line 127, in build
    return Builder.build(self, obj, *args, **kwargs)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/builder/builder.py", line 219, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/builder/connection.py", line 248, in build_connection
    model, conn, rng, transform)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/builder/connection.py", line 117, in build_decoders
    rng=rng, E=E)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/cache.py", line 384, in cached_solver
    solver, neuron_type, gain, bias, x, targets, rng=rng, E=E)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/builder/connection.py", line 131, in solve_for_decoders
    activities = neuron_type.rates(x, gain, bias)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/neurons.py", line 263, in rates
    LIFRate.step_math(self, dt=1, J=J, output=out)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/neurons.py", line 271, in step_math
    self.tau_ref + self.tau_rc * np.log1p(1. / j[j > 0]))
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/jgosmann/tcm/tcm_immediate/tcm_immediate:process:0.py", line 16, in <module>
    Worker(store=task.store).start(execute, '/work/jgosmann/tcm/tcm_immediate/in/0.npz', '/work/jgosmann/tcm/tcm_immediate/out/0.npz')
  File "/home/jgosmann/software/psyrun/psyrun/processing.py", line 150, in start
    return_data=False)
  File "/home/jgosmann/software/psyrun/psyrun/mapper.py", line 135, in map_pspace_hdd_backed
    store.append(filename, dict_concat((get_result(fn, p),)))
  File "/home/jgosmann/software/psyrun/psyrun/mapper.py", line 36, in get_result
    result.update(fn(**params))
  File "/home/jgosmann/Documents/projects/research/tcm/psy-tasks/task_tcm_immediate.py", line 38, in execute
    return NeuralTCM().run_single_action('evaluate', p)[0]
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/ctn_benchmark/pipeline.py", line 92, in run_single_action
    return self.invoke_action(action)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/ctn_benchmark/pipeline.py", line 67, in invoke_action
    return self.actions[name].process_all()
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/ctn_benchmark/procstep.py", line 124, in process_all
    return list(self.process())
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/ctn_benchmark/procstep.py", line 166, in process
    for items in zip(*self.connectors):
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/ctn_benchmark/procstep.py", line 143, in __next__
    a = next(self.step._iter)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/ctn_benchmark/procstep.py", line 168, in process
    **{k.name: v for k, v in zip(self.connectors, items)})
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/ctn_benchmark/common_steps.py", line 190, in process_item
    return Simulator(model, dt=self.p.dt)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/simulator.py", line 147, in __init__
    cache.shrink()
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/cache.py", line 211, in __exit__
    return self._index.__exit__(exc_type, exc_value, traceback)
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/cache.py", line 114, in __exit__
    self.sync()
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/cache.py", line 130, in sync
    self._index = self._load_index()
  File "/home/jgosmann/.virtualenvs/saw-bleedingedge3/lib/python3.4/site-packages/nengo/cache.py", line 120, in _load_index
    return pickle.load(f)
EOFError: Ran out of input
--- SharcNET Job Epilogue ---
              job id: 5803050
         exit status: 1
        elapsed time: 3190s / 8.0h (11 %)
      virtual memory: 3.8G / 4.0G (95 %)

Job returned with status 1.
WARNING: Job only used 11 % of its requested walltime.
```

Not exactly sure what is going on here. It seems that the exception that should lead to a gracefully handled cache miss, leads to a `MemoryError` that crashes the whole process. Moreover, this is on the `bleeding-edge` branch and thus the cache code might be a little bit outdated.

All the cache files are reasonable in size (< 50MB), the index file is empty (which explains the third EOF exception).

**Comment by jgosmann** [comment]
I probably did not allocate enough memory for the jobs and during the handling of the cache miss more memory needed to be allocated to solve for the decoders leading to the MemoryError. So this is most likely not a bug.
