### ISSUE TITLE
`with_self` interferes with super constructor

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#1259]
```python
import nengo
from nengo.utils.network import with_self


class GoodNet(nengo.Network):
    def __init__(self, **kwargs):
        super(GoodNet, self).__init__(**kwargs)
        with self:
            self.a = nengo.Ensemble(100, 1)
            print(self.label)


class BadNet(nengo.Network):
    @with_self
    def __init__(self, **kwargs):
        super(BadNet, self).__init__(**kwargs)
        self.a = nengo.Ensemble(100, 1)
        print(self.label)


with nengo.Network() as model:
    good_net = GoodNet(label='good')
    bad_net = BadNet(label='bad')
```
fails with
```
good
Traceback (most recent call last):
  File "test_with_self.py", line 23, in <module>
    bad_net = BadNet(label='bad')
  File "/data/eric/workspace/nengo/nengo/network.py", line 202, in __exit__
    "to be '%s' but instead got '%s'." % (self, network))
  File "/data/eric/workspace/nengo/nengo/network.py", line 215, in __str__
    '"%s"' % self.label if self.label is not None else
AttributeError: 'BadNet' object has no attribute 'label'
```

Somehow, `with_self` is stopping the constructor from being called, and thus `label` from being initialized.

**Comment by hunse** [comment]
Ahh, it has to do with the constructor being called in the `with self` block. This also fails:

```python
import nengo
from nengo.utils.network import with_self


class UnGoodNet(nengo.Network):
    def __init__(self, **kwargs):
        with self:
            super(GoodNet, self).__init__(**kwargs)
            self.a = nengo.Ensemble(100, 1)
            print(self.label)


with nengo.Network() as model:
    ungood_net = UnGoodNet(label='good')
```

**Comment by jgosmann** [comment]
You're traceback is slightly weird. I get a different one (the one I would expect):
```
In [1]: class Test(nengo.Network):
   ...:     def __init__(self, **kwargs):
   ...:         with self:
   ...:             super(Test, self).__init__(**kwargs)
   ...:             

In [2]: Test()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-d1e5fd9e553c> in <module>()
----> 1 Test()

<ipython-input-1-609d777066a8> in __init__(self, **kwargs)
      1 class Test(nengo.Network):
      2     def __init__(self, **kwargs):
----> 3         with self:
      4             super(Test, self).__init__(**kwargs)
      5 

/home/jgosmann/.pyenv/versions/3.5.2/lib/python3.5/site-packages/nengo/network.py in __enter__(self)
    181     def __enter__(self):
    182         Network.context.append(self)
--> 183         self._config.__enter__()
    184         return self
    185 

AttributeError: 'Test' object has no attribute '_config'
```

I don't think that there is a way we can make this work (at least not without some obscure Python magic). You are essentially asking to set an unintialized network object as context and then try to initialize it. Even if this would be possible the constructor call would by default add the network to itself (`add_to_container=True`). If you were to set `add_to_container=False` for the constructor call, you would need to handle it manually in your network.

**Comment by jgosmann** [comment]
@hunse, are fine with closing this issue as invalid/won't fix?

**Comment by hunse** [comment]
Sure, I'm fine to close.
