### ISSUE TITLE
Useful error messages for representing infinity

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo#1280]
If you accidentally create a Node that can output infinity, nengo gives a rather cryptic error message:

```python
import numpy as np
import nengo

model = nengo.Network()
with model:
    def problematic_func(t):
        return np.ones(1)/0
    n = nengo.Node(problematic_func)
    ens = nengo.Ensemble(n_neurons=100, dimensions=1)
    nengo.Connection(n, ens)
```

```

Building finished in 0:00:01.                                                   
Traceback (most recent call last):
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\page.py", line 496, in runner
    self.sim.step()
  File "c:\users\terry\documents\github\nengo\nengo\simulator.py", line 308, in step
    step_fn()
  File "c:\users\terry\documents\github\nengo\nengo\builder\neurons.py", line 68, in step_simneurons
    self.neurons.step_math(dt, J, output, *states)
  File "c:\users\terry\documents\github\nengo\nengo\neurons.py", line 326, in step_math
    -(voltage[spiked_mask] - 1) / (J[spiked_mask] - 1))
FloatingPointError: invalid value encountered in true_divide
```

It would be really nice if it at least indicated which Ensemble was receiving infinity or NaN as an input, as that can help identify where the problem is.

**Comment by jgosmann** [comment]
This is a variation on #1178.
