### ISSUE TITLE
Custom operator breaks signal optimizer

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo#1300]
The following is a stripped down version of code from @psipeter's [bionengo](https://github.com/psipeter/bionengo) repository, which uses a custom operator to handle connections to a custom neuron type (used to send the spikes off to NEURON).

This breaks with the newest addition of the signal optimizer (sorry @jgosmann).

```
optimize = True  # <-- set to True to enable bug

import numpy as np

import nengo
from nengo.dists import get_samples
from nengo.builder.connection import build_decoders
from nengo.builder.connection import BuiltConnection


class CustomOperator(nengo.builder.Operator):

    def __init__(self, spikes):
        self.spikes = spikes
        self.reads = [spikes]
        self.updates = []
        self.sets = []
        self.incs = []

    def make_step(self, signals, dt, rng):
        spikes = signals[self.spikes]  # <-- invokes KeyError

        def step():
            spikes  # do external stuff with spikes
        return step


class CustomNeuron(nengo.neurons.LIF):
    pass


@nengo.builder.Builder.register(nengo.Connection)
def build_connection(model, conn):
    if isinstance(conn.post, nengo.Ensemble) and \
       isinstance(conn.post.neuron_type, CustomNeuron):
        rng = np.random.RandomState(model.seeds[conn])
        model.sig[conn]['in'] = model.sig[conn.pre]['out']
        transform = get_samples(
            conn.transform, conn.size_out, d=conn.size_mid, rng=rng)
        eval_points, weights, solver_info = build_decoders(
            model, conn, rng, transform)
        model.add_op(CustomOperator(model.sig[conn.pre]['out']))
        model.params[conn] = BuiltConnection(
                eval_points=eval_points,
                solver_info=solver_info,
                transform=transform,
                weights=weights)

    else:
        return nengo.builder.connection.build_connection(model, conn)


with nengo.Network() as model:
    a = nengo.Ensemble(1, 1)
    b = nengo.Ensemble(1, 1, neuron_type=CustomNeuron())
    nengo.Connection(a, b)

    nengo.Probe(a.neurons, 'spikes')
    nengo.Probe(b.neurons, 'spikes')

with nengo.Simulator(model, optimize=optimize) as sim:
    pass
```

```
Traceback (most recent call last):
  File "temp.py", line 61, in <module>
    with nengo.Simulator(model, optimize=optimize) as sim:
  File "/home/arvoelke/CTN/nengo/nengo/simulator.py", line 159, in __init__
    opmerge_optimize(self.model, self.dg)
  File "/home/arvoelke/CTN/nengo/nengo/builder/optimizer.py", line 118, in optimize
    model.add_op(op)
  File "/home/arvoelke/CTN/nengo/nengo/builder/builder.py", line 109, in add_op
    op.make_step(signals, self.dt, np.random)
  File "temp.py", line 21, in make_step
    spikes = signals[self.spikes]  # <-- invokes KeyError
  File "/home/arvoelke/CTN/nengo/nengo/builder/signal.py", line 245, in __getitem__
    return dict.__getitem__(self, key)
KeyError: Signal(<Ensemble (unlabeled) at 0x7fefc0d6aad0>.neuron_out, shape=(1,))
```

Note that, for whatever reason, _both_ probes are needed in order to cause the bug.

**Comment by jgosmann** [comment]
1. Please call the super constructor in `__init__`.
2. With the optimizer all signals need to be stored and accessed via `self.reads`, `self.updates`, `self.sets`, or `self.incs`. To keep the code readable, define a property like this:
```python
    @property
    def spikes(self):
        return self.reads[0]
```

**Comment by arvoelke** [comment]
I can confirm that point 2 fixes this. Thanks. Feel free to close if no further action is needed.
