### ISSUE TITLE
Change default behaviour when nengo doesn't detect a browser.

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo#1478]
When nengo doesn't detect a browser it can automatically open it throws this error and quits:
```
Traceback (most recent call last):
  File "/home/xchoo/miniconda2/envs/inrc/bin/nengo", line 11, in <module>
    sys.exit(main())
  File "/home/xchoo/miniconda2/envs/inrc/lib/python3.5/site-packages/nengo_gui/main.py", line 123, in main
    wb = webbrowser.get()
  File "/home/xchoo/miniconda2/envs/inrc/lib/python3.5/webbrowser.py", line 51, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser
```

I propose changing the behaviour to run in `--no-browswer` mode instead (similar to what jupyter notebook does when it doesn't find a runnable browser)

**Comment by tbekolay** [comment]
This is a [GUI issue](https://github.com/nengo/nengo-gui/issues).

**Comment by tbekolay** [comment]
Migrated to https://github.com/nengo/nengo-gui/issues/995
