### ISSUE TITLE
Cannot change `n_neurons` post ensemble creation

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo#1547]
**Describe the bug**

Trying to change the `n_neurons` attribute of an ensemble (post creation) causes an error message to be thrown.

**To reproduce**

A minimal code snippet to reproduce the behavior:

```python
import nengo

nengo.log(level="debug")

with nengo.Network() as net:
    ens = nengo.Ensemble(50, 1)
    ens.n_neurons = 100
```

**Expected behavior**

Previous versions of Nengo would not throw an error when doing this.

**Error message and logs**

The code throws the following error message:
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/mnt/d/Users/xchoo/GitHub/nengo/nengo/base.py", line 107, in __setattr__
    super().__setattr__(name, val)
  File "/mnt/d/Users/xchoo/GitHub/nengo/nengo/config.py", line 455, in __setattr__
    raise exc_info[1].with_traceback(None)
nengo.exceptions.ReadonlyError: Ensemble.n_neurons: n_neurons is read-only and cannot be changed
```

**Versions**

 - OS: Windows 10, Ubuntu
 - Python: Anaconda Python 3.X
 - Nengo: latest master
 - Other: [e.g. NumPy v1.16.1 with MKL]

**Additional context**

Ran across this bug trying to do `n_neuron` parameter sweeps.

**Comment by jgosmann** [comment]
This is due to fb8f5e80bf7430f503f511200ddc77c5c8ef9ebe/#1372 and I'm wondering whether this might have been on purpose. But in the discussion nothing hints at this, so probably this is indeed a bug.

**Comment by tcstewar** [comment]
I also ran into this during the summer school...  I had a vague memory of discussing ages ago whether or not `n_neurons` should be configurable, but I'd definitely like it to be!  This does mean, of course, that it's possible to build broken models (the transform on a Connection doing to an Ensemble.neurons may now be the wrong size), but I do think that's worth it....

**Comment by drasmuss** [comment]
After some more discussion, we think this is the desired behaviour (for now). Allowing n_neurons to change post-initialization can introduce all kinds of errors, and the errors tend to be obscure and hard to diagnose/fix because they don't occur until the build stage. 

The long-term change would be properly validating changes to `n_neurons` on the front-end, at which point it would make sense to remove the read-only restriction. So I'm going to leave this issue open to track that idea (with the note that this is a feature request, rather than a bug). We don't have any immediate plans to work on that feature, as there doesn't seem to be a strong need (although feel free to add any comments here if you do have a need for this feature). But for now people should expect `n_neurons` to remain read-only .
