### ISSUE TITLE
Nengo fails to start with Python 3.8 under Windows.

### ISSUE THREAD

**Issue by gaolaowai** [nengo/nengo#1641]
**Describe the bug**

Nengo fails to start with Python 3.8 on Windows, due to the removal of time.clock().

**To reproduce**

Install python 3.8, then 
`pip install nengo nengo-gui && nengo`

**Expected behavior**

Nengo gui server should start and run as described in the "Getting Started" page of nengo.ai.

**Error message and logs**
```
Traceback (most recent call last):
  File "c:\users\max\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\max\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\max\AppData\Local\Programs\Python\Python38-32\Scripts\nengo.exe\__main__.py", line 4, in <module>
  File "c:\users\max\appdata\local\programs\python\python38-32\lib\site-packages\nengo_gui\__init__.py", line 1, in <module>
    from .gui import GUI, InteractiveGUI
  File "c:\users\max\appdata\local\programs\python\python38-32\lib\site-packages\nengo_gui\gui.py", line 20, in <module>
    from nengo_gui.guibackend import GuiServer
  File "c:\users\max\appdata\local\programs\python\python38-32\lib\site-packages\nengo_gui\guibackend.py", line 26, in <module>
    import nengo_gui.page
  File "c:\users\max\appdata\local\programs\python\python38-32\lib\site-packages\nengo_gui\page.py", line 12, in <module>
    import nengo
  File "c:\users\max\appdata\local\programs\python\python38-32\lib\site-packages\nengo\__init__.py", line 39, in <module>
    from .base import Process
  File "c:\users\max\appdata\local\programs\python\python38-32\lib\site-packages\nengo\base.py", line 7, in <module>
    from nengo.config import SupportDefaultsMixin
  File "c:\users\max\appdata\local\programs\python\python38-32\lib\site-packages\nengo\config.py", line 18, in <module>
    from nengo.params import Default, is_param, iter_params
  File "c:\users\max\appdata\local\programs\python\python38-32\lib\site-packages\nengo\params.py", line 7, in <module>
    from nengo.rc import rc
  File "c:\users\max\appdata\local\programs\python\python38-32\lib\site-packages\nengo\rc.py", line 67, in <module>
    import nengo.utils.paths
  File "c:\users\max\appdata\local\programs\python\python38-32\lib\site-packages\nengo\utils\__init__.py", line 14, in <module>
    from . import simulator
  File "c:\users\max\appdata\local\programs\python\python38-32\lib\site-packages\nengo\utils\simulator.py", line 5, in <module>
    from .stdlib import groupby
  File "c:\users\max\appdata\local\programs\python\python38-32\lib\site-packages\nengo\utils\stdlib.py", line 256, in <module>
    class Timer:
  File "c:\users\max\appdata\local\programs\python\python38-32\lib\site-packages\nengo\utils\stdlib.py", line 283, in Timer
    TIMER = time.clock if sys.platform == "win32" else time.time
AttributeError: module 'time' has no attribute 'clock'
```

**Versions**

 Nengo (latest in pip)
 CPython 3.8

**Additional context**

Simply following directions from the getting started guide, if using Python 3.8, will result in the above mentioned error. To fix, someone knowledgeable about the timer's use will need to evaluate the impact of using something like time.perf_counter() or some other solution.

See [here for reference on the topic](https://stackoverflow.com/questions/85451/pythons-time-clock-vs-time-time-accuracy) of time tracking in Python 3.3 and up.

**Comment by tbekolay** [comment]
Hi @gaolaowai! We implemented Python 3.8 support in #1628. It is currently part of the master branch, so you do a [developer installation](https://www.nengo.ai/nengo/contributing.html#developer-installation) to use Nengo with Python 3.8 right now. We will be making a release relatively soon (within a few weeks) if you prefer to wait.

Thanks for the bug report!
