### ISSUE TITLE
Cache not working properly on Windows.

### ISSUE THREAD

**Issue by hunse** [nengo/nengo#1655]
**Describe the bug**

Most/all of the cache tests are failing on Windows [in Appveyor](https://ci.appveyor.com/project/nengo/nengo/builds/36547730/job/24q0yp4h3hrdoxrr).

Here's an example:
```
______________________________ test_cache_works _______________________________
tmp_path = WindowsPath('C:/Users/appveyor/AppData/Local/Temp/1/pytest-of-appveyor/pytest-0/test_cache_works0')
Simulator = <class 'nengo.simulator.Simulator'>, seed = 1897043097
    def test_cache_works(tmp_path, Simulator, seed):
        cache_dir = str(tmp_path)
    
        model = nengo.Network(seed=seed)
        with model:
            nengo.Connection(nengo.Ensemble(10, 1), nengo.Ensemble(10, 1))
    
        assert len(os.listdir(cache_dir)) == 0
        with Simulator(
            model,
            model=nengo.builder.Model(
>               dt=0.001, decoder_cache=DecoderCache(cache_dir=cache_dir)
            ),
        ):
nengo\tests\test_cache.py:403: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
nengo\simulator.py:169: in __init__
    self.model.build(network, progress=pt.next_stage("Building", "Build"))
nengo\builder\builder.py:134: in build
    built = self.builder.build(self, obj, *args, **kwargs)
nengo\builder\builder.py:239: in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
nengo\builder\network.py:94: in build_network
    model.build(conn)
nengo\builder\builder.py:134: in build
    built = self.builder.build(self, obj, *args, **kwargs)
nengo\builder\builder.py:239: in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
nengo\builder\connection.py:269: in build_connection
    eval_points, decoders, solver_info = model.build(conn.solver, conn, rng)
nengo\builder\builder.py:134: in build
    built = self.builder.build(self, obj, *args, **kwargs)
nengo\builder\builder.py:239: in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
nengo\builder\connection.py:177: in build_solver
    return build_decoders(model, conn, rng)
nengo\builder\connection.py:139: in build_decoders
    decoders, solver_info = wrapped_solver(conn, gain, bias, x, targets, rng=rng)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
conn = <Connection at 0x7326450 from <Ensemble (unlabeled) at 0x73262f0> to <Ensemble (unlabeled) at 0x7326830>>
gain = array([ 4.70284105, 65.92307885, 37.85184485, 28.20411068,  5.81478654,
       39.38644237, 14.8667902 , 81.79648687, 22.09225079, 15.1999182 ])
bias = array([  5.41073128, -38.8251506 , -11.11026018,   8.77299891,
         4.84995453, -13.13161698,   2.84907906, -56.91666873,
       -11.91211031,  11.87399016])
x = array([[-0.46116172,  0.46116172, -0.46116172, ..., -0.46116172,
         0.46116172,  0.46116172],
       [ 0.5848774...172,  0.99716172],
       [-0.94916172,  0.94916172, -0.94916172, ..., -0.94916172,
         0.94916172,  0.94916172]])
targets = array([[-4.61161717e-01],
       [ 5.84877413e-01],
       [ 4.94210747e-01],
       [ 6.96877413e-01],
       [-9.784...74495050e-01],
       [-2.95828383e-01],
       [-1.33161717e-01],
       [-9.97161717e-01],
       [-9.49161717e-01]])
rng = RandomState(MT19937) at 0x72222B8, uncached_kwargs = {}
key = '5997ec4aae3f442b9b16fac68d4168f7a0038542'
    def cached_solver(
        conn, gain, bias, x, targets, rng=np.random, **uncached_kwargs
    ):
        if not self._in_context:
            warnings.warn("Cannot use cached solver outside of `with cache` block.")
            return solver_fn(
                conn, gain, bias, x, targets, rng=rng, **uncached_kwargs
            )
    
        try:
            key = self._get_cache_key(
                conn.solver, conn.pre_obj.neuron_type, gain, bias, x, targets, rng
            )
        except FingerprintError as e:
            logger.debug("Failed to generate cache key: %s", e)
            return solver_fn(
                conn, gain, bias, x, targets, rng=rng, **uncached_kwargs
            )
    
        try:
>           path, start, end = self._index[key]
E           TypeError: 'NoneType' object is not subscriptable
nengo\cache.py:766: TypeError
------------------------------ Captured log call ------------------------------
ERROR    nengo.cache:cache.py:463 Decoder cache index corrupted. Reinitializing cache.
Traceback (most recent call last):
  File "C:\projects\nengo\nengo\cache.py", line 461, in __enter__
    self._load_index_file()
  File "C:\projects\nengo\nengo\cache.py", line 384, in _load_index_file
    with open(self.index_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pytest-of-appveyor\\pytest-0\\test_cache_works0\\index'
```

It appears to be a problem with the index file. I'm going to add #1644 to #1649 to get things passing there, but that will just avoid using the cache in this situation; it won't fix the actual problem with the cache. This issue is to remind us to look into that deeper problem on Windows.

**To reproduce**

Unfortunately, I don't have a Windows machine handy to test, so I'm not sure if this happens on all machines or only some. However, it should be reproducible in the Appveyor setup. Even with the fix introduced from #1644, there should still be the `Decoder cache index corrupted. Reinitializing cache.` error appearing behind the scenes (though I don't think pytest will show it by default if the test isn't failing).

**Comment by hunse** [comment]
I tried this in my Windows VM, and I can't reproduce it there. :disappointed:

**Comment by hunse** [comment]
This bug appears to be specific to the Python 3.5 removal in #1649. I can reproduce it in that branch on my Windows VM, so I'll fix things there.
