### ISSUE TITLE
Failing nengo start

### ISSUE THREAD

**Issue by baswunderlich** [nengo/nengo#1697]
Hi guys Im a little confused if Im doing something wrong.

After the installation via "pip install nengo nengo-gui" as shown in the setup guide, I can not start nengo.

The output:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Scripts\nengo.exe\__main__.py", line 4, in <module>
    from nengo_gui import main
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\nengo_gui\__init__.py", line 1, in <module>
    from .gui import GUI, InteractiveGUI
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\nengo_gui\gui.py", line 21, in <module>
    from nengo_gui.guibackend import GuiServer
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\nengo_gui\guibackend.py", line 25, in <module>
    import nengo_gui.page
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\nengo_gui\page.py", line 12, in <module>
    import nengo
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\nengo\__init__.py", line 15, in <module>
    from nengo import spa  # pylint: disable=cyclic-import
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\nengo\spa\__init__.py", line 1, in <module>
    from .actions import Actions
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\nengo\spa\actions.py", line 7, in <module>
    from nengo.spa.action_objects import DotProduct, Source, Summation, Symbol
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\nengo\spa\action_objects.py", line 4, in <module>
    from nengo.utils.numpy import is_number
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\nengo\utils\__init__.py", line 1, in <module>
    from . import (
    ...<15 lines>...
    )
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\nengo\utils\filter_design.py", line 42, in <module>
    from numpy import (
    ...<12 lines>...
    )
ImportError: cannot import name 'product' from 'numpy' (C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\__init__.py)

A minimal code snippet to reproduce the behavior:

```python
import nengo
```
or you type "nengo" in the console

What I expected:
I expected the nengo api to start when typing "nengo" in the console

Versions: 
 - OS: [e.g. Windows 11]
 - Python: [Python 3.13.0]
 - Nengo: [4.0.0]
 - numy: [2.1.2]

It works on my friends machine but he uses an older numpy version I can not install as it seems because of distutils missing. I read about it, that it may be too old to be installed (missing dependencies).

I hope someone can help and thanks in advance :)

**Comment by hunse** [comment]
You might also have to roll back your Python version to e.g. 3.9 to be able to install older Numpy. I don't think Nengo has ever been tested with `numpy >= 2.0`, so I'm guessing it's some changes there that have broken things.

**Comment by baswunderlich** [comment]
Thank you for the quick response. That fixed it :)
