### ISSUE TITLE
Error using PES learning rule in Direct mode

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo#554]
I'm wondering if it should be possible to use the PES learning rule on an ensemble running in Direct mode. I know there are no decoders to modify, but it would be nice if something functionally equivalent could be done. The use case would be debugging models with learning that take a long time to build by running them in Direct mode instead.

Right now this just produces an error

``` python
 import nengo
 import numpy as np

 model = nengo.Network()

 with model:
   error = nengo.Ensemble( 100, 1 )
   pre = nengo.Ensemble( 100, 1, neuron_type=nengo.Direct() )
   post = nengo.Ensemble( 100, 1 )
   error_conn = nengo.Connection( error, post, modulatory=True )
   nengo.Connection( pre, post, function = lambda x: np.random.random(1),
                     learning_rule_type=nengo.PES( error_conn, learning_rate=1.0 ) )

 sim = nengo.Simulator( model )
 sim.run(5)
```

```
Traceback (most recent call last):
  File "direct_mode_pes_issue.py", line 15, in <module>
    sim = nengo.Simulator( model )
  File "/home/bjkomer/nnroot/src/nengo/nengo/simulator.py", line 110, in __init__
    self.model.build(network)
  File "/home/bjkomer/nnroot/src/nengo/nengo/builder/builder.py", line 34, in build
    return Builder.build(self, *objs)
  File "/home/bjkomer/nnroot/src/nengo/nengo/builder/builder.py", line 74, in build
    cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home/bjkomer/nnroot/src/nengo/nengo/builder/network.py", line 63, in build_network
    model.build(conn)
  File "/home/bjkomer/nnroot/src/nengo/nengo/builder/builder.py", line 34, in build
    return Builder.build(self, *objs)
  File "/home/bjkomer/nnroot/src/nengo/nengo/builder/builder.py", line 74, in build
    cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home/bjkomer/nnroot/src/nengo/nengo/builder/connection.py", line 196, in build_connection
    modified_signal = model.sig[conn]['decoders']
KeyError: 'decoders'
```

**Comment by tbekolay** [comment]
We discussed this at the last dev meeting. Still a good idea! But a pretty big job, so made https://github.com/nengo/enhancement_proposals/pull/9 for it. Then I made #1192 to tighten up the error message. Discussion can continue in either of those places!
