### ISSUE TITLE
Failure running unit tests.

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#704]
While `py.test --pyargs nengo` seems to work, a pure `py.test` quits with this error:
```
(nengodev)ctn02:nengo|master> py.test                                                                                                   ✭? dc9fecbc5d
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.9 -- py-1.4.26 -- pytest-2.6.4
plugins: cov
collecting 618 itemsINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/jgosmann/.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/main.py", line 84, in wrap_session
INTERNALERROR>     doit(config, session)
INTERNALERROR>   File "/home/jgosmann/.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/main.py", line 121, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/jgosmann/.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 413, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/home/jgosmann/.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/home/jgosmann/.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/home/jgosmann/.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/main.py", line 125, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/home/jgosmann/.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/main.py", line 548, in perform_collect
INTERNALERROR>     config=self.config, items=items)
INTERNALERROR>   File "/home/jgosmann/.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 413, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/home/jgosmann/.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/home/jgosmann/.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/home/jgosmann/Documents/projects/nengo/nengo/tests/conftest.py", line 237, in pytest_collection_modifyitems
INTERNALERROR>     compare = config.getvalue('compare') is None
INTERNALERROR>   File "/home/jgosmann/.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/config.py", line 840, in getvalue
INTERNALERROR>     return self.getoption(name)
INTERNALERROR>   File "/home/jgosmann/.pyenv/versions/2.7.9/lib/python2.7/site-packages/_pytest/config.py", line 836, in getoption
INTERNALERROR>     raise ValueError("no option named %r" % (name,))
INTERNALERROR> ValueError: no option named 'compare'

==================================================================  in 1.04 seconds ==================================================================
```

**Comment by jgosmann** [comment]
The `py.test --pyargs nengo` command only work from the Nengo root directory. The problem is the `conftest.py` file in `nengo/tests` is loaded after the arguments are parsed.
