### ISSUE TITLE
Try Nengo with PyPy 4.0.0+

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#890]
[PyPy 4.0.0 was just released](http://morepypy.blogspot.com/2015/10/pypy-400-released-jit-with-simd.html), with a bunch of features that might be very nice for Nengo. Specifically, they've [implemented a good chunk of Numpy now](https://bitbucket.org/pypy/numpy), and there is a JIT compiler with vectorization, so it is possible that running reference Nengo with PyPy could give us some nice speedups. But, from what I understand, it's quite a bit of hassle getting the whole PyPy toolchain up and running, and there's no guarantee they've implemented everything that we use. Still, it would be cool to get it all working, as the best kind of speedup is the one that doesn't require changes to our code!

**Comment by jgosmann** [comment]
Just tried to import nengo with PyPy 5.4.0 and it fails with this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nengo/__init__.py", line 21, in <module>
    from .connection import Connection
  File "nengo/connection.py", line 11, in <module>
    from nengo.node import Node
  File "nengo/node.py", line 9, in <module>
    from nengo.processes import Process
  File "nengo/processes.py", line 61, in <module>
    class FilteredNoise(Process):
  File "nengo/processes.py", line 87, in FilteredNoise
    synapse=Lowpass(tau=0.005), dist=Gaussian(mean=0, std=1),
  File "nengo/synapses.py", line 347, in __init__
    super(Lowpass, self).__init__([1], [tau, 1], **kwargs)
  File "nengo/synapses.py", line 183, in __init__
    self.num = num
  File "nengo/params.py", line 349, in __set__
    ndarray = self.validate(instance, ndarray)
  File "nengo/params.py", line 367, in validate
    ndarray.setflags(write=False)
AttributeError: 'numpy.ndarray' object has no attribute 'setflags'
```

**Comment by jgosmann** [comment]
Also, getting PyPy and their NumPy conversion installed was pretty easy with [PyEnv](https://github.com/yyuu/pyenv). It's basically done wtih these few steps:
1. `pyenv install pypy-5.4.0`
2. `mkvirtualenv -p pypy pypy`
3. `git clone https://bitbucket.org/pypy/numpy.git`
4. `cd numpy; pypy setup.py install`

**Comment by hunse** [comment]
That's strange. Just looking at the code, they seem to have `setflags`. But I haven't tried installing yet.

**Comment by hunse** [comment]
Ok, so I just installed pypy, and doing something like `a.flags.writeable = False` doesn't work either (I get an error that it's a readonly attribute). So I'm guessing that `numpypy` has intentionally disabled this functionality for some reason? It still seems to me like there should be a way to get a readonly view on an array (since that's ultimately what we want to accomplish).

Alternately, we could not worry about making views readonly, but I think it can be really helpful for avoiding errors, just so we make sure those buffers don't accidentally get written to.

**Comment by jgosmann** [comment]
> Alternately, we could not worry about making views readonly, but I think it can be really helpful for avoiding errors, just so we make sure those buffers don't accidentally get written to.

Yeah, we probably should first see whether we can get Nengo running with PyPy at all and how much that improves the performance before thinking about introducing such changes in core Nengo.

**Comment by hunse** [comment]
If you're just playing around, you should be able to comment out that `setflags` line without breaking anything.

**Comment by jgosmann** [comment]
I tried that, the current state is in #1166 for other people to play around or continue working on. Fixing the next thing that's failing seems like a major time investment for me, so I am probably not trying to do that any time soon.
