### ISSUE TITLE
Decoder cache crash on sharcnet

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#913]
I had a bunch of jobs on sharcnet crash because of 'stale file handles' in the decoder cache.

```
Traceback (most recent call last):
  File "/home/jgosmann/Documents/projects/n-back/models/nback3.py", line 226, in <module>
    sim = nengo.Simulator(model)
  File "/home/jgosmann/.virtualenvs/n-back/lib/python2.7/site-packages/nengo-2.0.0_dev-py2.7.egg/nengo/simulator.py", line 113, in __init__
    self.model.decoder_cache.shrink()
  File "/home/jgosmann/.virtualenvs/n-back/lib/python2.7/site-packages/nengo-2.0.0_dev-py2.7.egg/nengo/cache.py", line 155, in shrink
    stat = safe_stat(path)
  File "/home/jgosmann/.virtualenvs/n-back/lib/python2.7/site-packages/nengo-2.0.0_dev-py2.7.egg/nengo/cache.py", line 23, in safe_stat
    return os.stat(path)
OSError: [Errno 116] Stale file handle: '/home/jgosmann/.cache/nengo/decoders/00/19de1d82bc7f5fb5d28561bec9328558539f59.nco'
--- SharcNET Job Epilogue ---
              job id: 11695269
         exit status: 1
            cpu time: 226s / 16.0h (0 %)
        elapsed time: 1838s / 16.0h (3 %)
      virtual memory: 776.4M / 2.5G (29 %)

Job returned with status 1.
WARNING: Job only used 3 % of its requested walltime.
WARNING: Job only used 0 % of its requested cpu time.
WARNING: Job only used 12 % of allocated cpu time.
WARNING: Job only used 29% of its requested memory.
```

**Comment by jgosmann** [comment]
I should note that this is potentially on an outdated cache version.

**Comment by jgosmann** [comment]
This did not occur lately and the issue is quite old. So I'll close it and reopen it if I should ever run across this again.
