### ISSUE TITLE
Support partial functions in a Connection

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo#981]
It would be nice to be able to use partial functions for the `function` argument in a `Connection`. Currently an `AttributeError` is thrown when you try to do this.

Simple example:
```
import nengo
from functools import partial

def add(x, val):
    return x + val

model = nengo.Network()

with model:
    a = nengo.Ensemble(10,1)
    b = nengo.Ensemble(10,1)
    nengo.Connection(a, b, function=partial(add,val=2))

sim = nengo.Simulator(model)
sim.run(1)
```

and the error is:
```
Traceback (most recent call last):
  File "partial_func_nengo_issue.py", line 14, in <module>
    sim = nengo.Simulator(model)
  File "/home/bjkomer/nengo/nengo/simulator.py", line 108, in __init__
    self.model.build(network)
  File "/home/bjkomer/nengo/nengo/builder/builder.py", line 34, in build
    return Builder.build(self, obj, *args, **kwargs)
  File "/home/bjkomer/nengo/nengo/builder/builder.py", line 79, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home/bjkomer/nengo/nengo/builder/network.py", line 72, in build_network
    model.build(conn)
  File "/home/bjkomer/nengo/nengo/builder/builder.py", line 34, in build
    return Builder.build(self, obj, *args, **kwargs)
  File "/home/bjkomer/nengo/nengo/builder/builder.py", line 79, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home/bjkomer/nengo/nengo/builder/connection.py", line 196, in build_connection
    model.sig[conn]['weights'] = Signal(weights, name="%s.weights" % conn)
  File "/home/bjkomer/nengo/nengo/connection.py", line 329, in __str__
    return "<Connection %s>" % self._label
  File "/home/bjkomer/nengo/nengo/connection.py", line 326, in _label
    if self.function is not None else "")
AttributeError: 'functools.partial' object has no attribute '__name__'
```

**Comment by Seanny123** [comment]
You get the same problem if you try to pass in an [`interp1d` object](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.interpolate.interp1d.html).

One way to work around this is to just create a lambda function that calls these objects that are typically rejected.

**Comment by Seanny123** [comment]
Upon further investigation, [it's this line](https://github.com/nengo/nengo/blob/master/nengo/connection.py#L379), which calls the name `__name__` property of the `function` keyword arg which is the problem.
